pretrained_model_name_or_path: Qwen/Qwen-Image-Edit-2509
data_config:
  train_batch_size: 2
  num_workers: 4
  img_size: 1024
  caption_dropout_rate: 0
  img_dir: ./images
  control_dir: ./control_images
  random_ratio: false # support multi crop preprocessing
  caption_type: txt
report_to: null
train_batch_size: 2
output_dir: ./test_lora_saves_edit
max_train_steps: 5000
learning_rate: 2e-4
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 250
checkpoints_total_limit: 20
tracker_project_name: lora_test
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
rank: 64
precompute_text_embeddings: true
precompute_image_embeddings: true
quantize: false
adam8bit: false
save_cache_on_disk: true

